### PR TITLE
fix failing prepush hook by only commiting when changes where detected

### LINKED ISSUE #21: fix failing prepush hook
prepush hook currently fails when the coverage did not change as no new badge to commit can be found.

### PR DESCRIPTION
**Pull request by jbreckel**
closes #21

### CODE REVIEW

File: scripts/prepush.sh [hunk 1]
```diff
@@ -0,0 +1,4 @@
+#!/bin/bash
+
+npm test -- --coverage && npm run coverbadge || exit 1
```
Comment (akleiber) [inline scripts/prepush.sh]: haha ok :D
